name: Tourism pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: pip install -r tourism/deployment/requirements.txt
      - name: Upload Dataset
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python tourism/model_building/data_register.py

  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: pip install -r tourism/deployment/requirements.txt
      - name: Run Data Prep
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python tourism/model_building/prep.py

  model-training:
    needs: data-prep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: pip install -r tourism/deployment/requirements.txt
      - name: Train Model
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python tourism/model_building/train.py

  deploy-hosting:
    needs: model-training
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: pip install -r tourism/deployment/requirements.txt
      - name: Deploy to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python tourism/hosting/hosting.py
